version: 2
jobs:
  build:
    docker:
      - image: node:lts
    working_directory: ~/komiser.io
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Push to S3 bucket
          command: aws s3 cp --recursive . s3://www.komiser.io --region eu-central-1